# Site Defaults; can and often should be overidden by pages
title: 'Grimoire'
description: 'Grimoire and lore from the Destiny and Destiny 2 universe created by Bungie'
image: '/images/default.jpg'


collections:
  grimoire:
    output: true
  d1_scannables
  d2_scannables


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

# Site Settings, shouldn't have to change (often)
separator: '&sdot;' # Used in browser/tab titles

# Set automatically by GitHub Pages
# baseurl: "grimoire" # Path of Jekyll instance; empty string if site root
# url: "https://cassidyjames.github.io" # Base hostname & protocol
